apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-app
  namespace: keda-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqs-reader
  template:
    metadata:
      labels:
        app: sqs-reader
    spec:
      serviceAccountName: keda-service-account
      containers:
      - name: sqs-pull-app
        image: khanasif1/sqs-reader:v0.8
        imagePullPolicy: Always